export const AUSTRALIA_GAMES = [
  {
    id: "5130",
    country: "australia",
    region: "wa",
    locale: "en-AU",
    parserType: "lotterywest",
    name: "OZ Lotto",
    shortName: "OZ Lotto",
    fileName: "5130-results.csv",
    sourceLabel: "Lotterywest public results data",
    officialUrl: "https://www.lotterywest.wa.gov.au/results/frequency-charts",
    currentFormatStartDraw: 1474,
    main: {
      label: "Winning",
      range: 47,
      count: 7,
      columnPrefix: "Winning Number",
    },
    secondary: {
      label: "Supplementary",
      range: 47,
      count: 3,
      columnPrefix: "Supplementary Number",
      sharesMainGrid: true,
    },
    display: {
      mainMark: "W",
      secondaryMark: "S",
      secondaryClass: "supplementary-hit",
    },
  },
  {
    id: "5132",
    country: "australia",
    region: "wa",
    locale: "en-AU",
    parserType: "lotterywest",
    name: "Powerball",
    shortName: "Powerball",
    fileName: "5132-results.csv",
    sourceLabel: "Lotterywest public results data",
    officialUrl: "https://www.lotterywest.wa.gov.au/results/frequency-charts",
    currentFormatStartDraw: 1144,
    main: {
      label: "Winning",
      range: 35,
      count: 7,
      columnPrefix: "Winning Number",
    },
    secondary: {
      label: "Powerball",
      range: 20,
      count: 1,
      columnPrefix: "Powerball Number",
      sharesMainGrid: false,
    },
    display: {
      mainMark: "W",
      secondaryMark: "P",
      secondaryClass: "secondary-hit",
    },
  },
  {
    id: "5237",
    country: "australia",
    region: "wa",
    locale: "en-AU",
    parserType: "lotterywest",
    name: "Set for Life",
    shortName: "Set for Life",
    fileName: "5237-results.csv",
    sourceLabel: "Lotterywest public results data",
    officialUrl: "https://www.lotterywest.wa.gov.au/results/frequency-charts",
    currentFormatStartDraw: 1691,
    main: {
      label: "Winning",
      range: 44,
      count: 7,
      columnPrefix: "Winning Number",
    },
    secondary: {
      label: "Supplementary",
      range: 44,
      count: 2,
      columnPrefix: "Supplementary Number",
      sharesMainGrid: true,
    },
    display: {
      mainMark: "W",
      secondaryMark: "S",
      secondaryClass: "supplementary-hit",
    },
  },
  {
    id: "au-vic-tattslotto",
    country: "australia",
    region: "vic",
    locale: "en-AU",
    parserType: "thelott",
    name: "TattsLotto",
    shortName: "TattsLotto",
    fileName: "au-vic-tattslotto.csv",
    sourceLabel: "The Lott / Tatts public results data",
    officialUrl: "https://www.thelott.com/tattslotto/results",
    main: {
      label: "Winning",
      range: 45,
      count: 6,
    },
    secondary: {
      label: "Supplementary",
      range: 45,
      count: 2,
      sharesMainGrid: true,
      drawOnly: true,
    },
    display: {
      mainMark: "W",
      secondaryMark: "S",
      secondaryClass: "supplementary-hit",
    },
  },
];
